**Name : Riwaj Maharjan**

**Group : L6CG19**

**Student Number : 2357551**

#  4.1 Exercise on Functions:

**Task- 1:**

 Create a Python program that converts between different units of measurement.

 **• The program should:**
 1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
 2. Ask the user to input the value to be converted.
 3. Perform the conversion and display the result.
 4. Handle potential errors, such as invalid input or unsupported conversion types.
 **Requirements:**

 1. Functions: Define at least one function to perform the conversion.
 2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
 3. User Input: Prompt the user to select the conversion type and input the value.
 4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
 return value.
 **• Conversion Options:**
 1. Length:– Convert meters (m) to feet (ft).– Convert feet (ft) to meters (m).
 2. Weight:– Convert kilograms (kg) to pounds (lbs).– Convert pounds (lbs) to kilograms (kg).
 3. Volume:– Convert liters (L) to gallons (gal).– Convert gallons (gal) to liters (L)

In [66]:
def unit_converter():
    """
    Converts between different units of measurement.
    Supports length (meters to feet, feet to meters),
    weight (kilograms to pounds, pounds to kilograms),
    and volume (liters to gallons, gallons to liters).
    """
    print("Choose conversion type:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")
    choice = input("Enter 1, 2, or 3: ")

    try:
        value = float(input("Enter the value to convert: "))
    except ValueError:
        print("Invalid input. Please enter a numeric value.")
        return

    if choice == "1":  # Length
        print("1. Meters to Feet")
        print("2. Feet to Meters")
        sub_choice = input("Enter 1 or 2: ")
        if sub_choice == "1":
            result = value * 3.28084
            print(f"{value} meters = {result} feet")
        elif sub_choice == "2":
            result = value / 3.28084
            print(f"{value} feet = {result} meters")
        else:
            print("Invalid choice.")
    elif choice == "2":  # Weight
        print("1. Kilograms to Pounds")
        print("2. Pounds to Kilograms")
        sub_choice = input("Enter 1 or 2: ")
        if sub_choice == "1":
            result = value * 2.20462
            print(f"{value} kilograms = {result} pounds")
        elif sub_choice == "2":
            result = value / 2.20462
            print(f"{value} pounds = {result} kilograms")
        else:
            print("Invalid choice.")
    elif choice == "3":  # Volume
        print("1. Liters to Gallons")
        print("2. Gallons to Liters")
        sub_choice = input("Enter 1 or 2: ")
        if sub_choice == "1":
            result = value * 0.264172
            print(f"{value} liters = {result} gallons")
        elif sub_choice == "2":
            result = value / 0.264172
            print(f"{value} gallons = {result} liters")
        else:
            print("Invalid choice.")
    else:
        print("Invalid choice.")

unit_converter()

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter 1, 2, or 3: 1
Enter the value to convert: 40
1. Meters to Feet
2. Feet to Meters
Enter 1 or 2: 1
40.0 meters = 131.2336 feet


 **Task- 2:**

 Create a Python program that performs various mathematical operations on a list of numbers

**• The Program should:**
 1. Prompt the user to choose an operation (e.g., find the sum, average maximum, or minimum of the numbers).
 2. Ask the user to input a list of numbers (separated by spaces).
 3. Perform the selected operation and display the result.
 4. Handle potential errors, such as invalid input or empty lists.

 **• Requirements:**
 1. Functions: Define at least one function for each operation (sum, average, maximum, mini
mum).
 2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
 empty lists).
 3. User Input: Prompt the user to select the operation and input the list of numbers.
 4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
 return value

In [72]:
def sum_list(numbers):
    """Returns the sum of a list of numbers."""
    return sum(numbers)

def average_list(numbers):
    """Returns the average of a list of numbers."""
    return sum(numbers) / len(numbers)

def max_list(numbers):
    """Returns the maximum value in a list of numbers."""
    return max(numbers)

def min_list(numbers):
    """Returns the minimum value in a list of numbers."""
    return min(numbers)

def math_operations():
    """
    Performs mathematical operations on a list of numbers.
    Supports sum, average, maximum, and minimum.
    """
    try:
        numbers = list(map(float, input("Enter a list of numbers separated by spaces: ").split()))
    except ValueError:
        print("Invalid input. Please enter numeric values.")
        return

    if not numbers:
        print("The list is empty.")
        return

    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")
    choice = input("Enter 1, 2, 3, or 4: ")

    if choice == "1":
        result = sum_list(numbers)
        print(f"Sum: {result}")
    elif choice == "2":
        result = average_list(numbers)
        print(f"Average: {result}")
    elif choice == "3":
        result = max_list(numbers)
        print(f"Maximum: {result}")
    elif choice == "4":
        result = min_list(numbers)
        print(f"Minimum: {result}")
    else:
        print("Invalid choice.")

math_operations()

Enter a list of numbers separated by spaces: 1 2 3 4
Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter 1, 2, 3, or 4: 1
Sum: 10.0


#4.2 Exercise on List Manipulation:

**1. Extract Every Other Element:**

Write a Python function that extracts every other element from a list, starting from the first element.

In [73]:
def extract_every_other(lst):
    return lst[::2]

print(extract_every_other([1, 2, 3, 4, 5, 6]))

[1, 3, 5]


**2. Slice a Sublist:**

 Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index

In [74]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

[3, 4, 5]


 **3. Reverse a List Using Slicing:**

 Write a Python function that reverses a list using slicing.

In [75]:
def reverse_list(lst):
    return lst[::-1]

print(reverse_list([1, 2, 3, 4, 5]))

[5, 4, 3, 2, 1]


**4. Remove the First and Last Elements:**

 Write a Python function that removes the first and last elements of a list and returns the resulting
 sublist

In [76]:
def remove_first_last(lst):
    return lst[1:-1]

print(remove_first_last([1, 2, 3, 4, 5]))

[2, 3, 4]


 **5. Get the First n Elements:**

 Write a Python function that extracts the first n elements from a list

In [77]:
def get_first_n(lst, n):
    return lst[:n]

print(get_first_n([1, 2, 3, 4, 5], 3))

[1, 2, 3]


**6. Extract Elements from the End:**

 Write a Python function that extracts the last n elements of a list using slicing

In [80]:
def get_last_n(lst, n):
    return lst[-n:]

print(get_last_n([1, 2, 3, 4, 5], 2))

[4, 5]


 **7. Extract Elements in Reverse Order:**

 Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

In [81]:
def reverse_skip(lst):
    return lst[-2::-2]

print(reverse_skip([1, 2, 3, 4, 5, 6]))

[5, 3, 1]


#  4.3 Exercise on Nested List:

**1. Flatten a Nested List:**

 Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

In [83]:
def flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

print(flatten([[1, 2], [3, 4], [5]]))

[1, 2, 3, 4, 5]


**2. Accessing Nested List Elements:**

 Write a Python function that extracts a specific element from a nested list given its indices.

In [84]:
def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]
    return lst

print(access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))

6


**3. Sum of All Elements in a Nested List:**

 Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [85]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1, 2], [3, [4, 5]], 6]))

21


**4. Remove Specific Element from a Nested List:**

 Write a Python function that removes all occurrences of a specific element from a nested list.

In [86]:
def remove_element(lst, elem):

    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

print(remove_element([[1, 2], [3, 2], [4, 5]], 2))

[[1], [3], [4, 5]]


 **5. Find the Maximum Element in a Nested List:**

 Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [88]:
def find_max(lst):
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val

print(find_max([[1, 2], [3, [4, 5]], 6]))

6


 **6. Count Occurrences of an Element in a Nested List:**

 Write a Python function that counts how many times a specific element appears in a nested list

In [89]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))

3


 **7. Flatten a List of Lists of Lists:**

 Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [90]:
def deep_flatten(lst):

    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


**8. Nested List Average:**

 Write a Python function that calculates the average of all elements in a nested list.

In [91]:
def average_nested(lst):
    total = sum_nested(lst)
    count = len(flatten(lst))
    return total / count

print(average_nested([[1, 2], [3, 4], [5, 6]]))

3.5


# 10.1 Basic Vector and Matrix Operation with Numpy

**Problem- 1: Array Creation:**

In [1]:
# 1. Initialize an empty array with size 2X2
import numpy as np
empty_array = np.empty((2, 2))
print(empty_array)

[[1.95781447e-316 0.00000000e+000]
 [2.57707506e-057 4.17265384e-057]]


In [2]:
# 2. Initialize an all one array with size 4X2
one_array = np.ones((4, 2))
print(one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
#3. Return a new array of given shape and type, filled with fill value
fill_array = np.full((3, 3), 5)
print(fill_array)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [5]:
# 4. Return a new array of zeros with same shape and type as a given array
zeros_array = np.zeros_like(fill_array)
print(zeros_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
#5. Return a new array of ones with same shape and type as a given array
ones_array = np.ones_like(fill_array)
print(ones_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
# 6. For an existing list new_list = [1,2,3,4] convert to an numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(numpy_array)

[1 2 3 4]


**Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:**

In [8]:
#1. Create an array with values ranging from 10 to 49
array_range = np.arange(10, 50)
print(array_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# 3. Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print(mean_value)

0.5257472451907735


In [15]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print(f"Min: {min_value}\nMax: {max_value}")

Min: 0.0015730333836333488
Max: 0.9647270616535585


In [16]:
# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [17]:
#7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [18]:
#8. Create a 2d array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
# 9. Create a 8X8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Problem- 3: Array Operations:**

 For the following arrays:

 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

 v = np.array([9,10]) and w = np.array([11,12]);


In [20]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [49]:
# 1. Add the two array.
add = x + y
print(add)

[[ 6  8]
 [10 13]]


In [22]:
# 2. Subtract the two array.
difference = x - y
print(difference)

[[-4 -4]
 [-4 -3]]


In [23]:
# 3. Multiply the array with any integers of your choice.
multiply = x * 2
print(multiply)

[[ 2  4]
 [ 6 10]]


In [25]:
# 4. Find the square of each element of the array.
sq = np.square(x)
print(sq)

[[ 1  4]
 [ 9 25]]


In [26]:
# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)
print(f"Dot product v and w: {dot_v_w}")
print(f"Dot product x and v: {dot_x_v}")
print(f"Dot product x and y: {dot_x_y}")

Dot product v and w: 219
Dot product x and v: [29 77]
Dot product x and y: [[19 22]
 [50 58]]


In [27]:
# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
concatenate_x_y = np.vstack((x, y))
concatenate_v_w = np.column_stack((v, w))
print(concatenate_x_y)
print(concatenate_v_w)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [29]:
# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
concatenate_x_v = np.concatenate((x, v))
print(concatenate_x_v)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

The shapes of x and v are not compatible for concatenation. The arrays should have the same number of dimensions for concatenation.

**Problem- 4: Matrix Operations:**

 For the following arrays:

 A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

In [30]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

In [31]:
# 1. Prove A.A−1 = I.
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print(identity)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [33]:
#2. Prove AB= BA.
AB = np.dot(A, B)
BA = np.dot(B, A)
print(f"AB:\n{AB}")
print(f"BA:\n{BA}")


AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]


In [36]:
# 3. Prove (AB)^T = B^T.A^T.
AB_transpose = AB.T
B_A = np.dot(B.T, A.T)
print(f"(AB)^T:\n{AB_transpose}")
print(f"B^T A^T:\n{B_A}")

(AB)^T:
[[23 51]
 [13 29]]
B^T A^T:
[[23 51]
 [13 29]]


 Solve the following system of Linear equation using Inverse Methods.

 2x −3y+z =−1

 x −y+2z =−3

 3x +y−z =9

In [38]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
import numpy as np

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution for x, y, and z:")
print(X)


Solution for x, y, and z:
[ 2.  1. -2.]


In [40]:
# Now: solve the above equation using np.linalg.inv function.
X_solve = np.linalg.solve(A, B)
print(X_solve)

[ 2.  1. -2.]


# 10.2 Experiment: How Fast is Numpy?

 1. Element-wise Addition:

 • Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure and Print the time taken for this operation.

 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation

In [45]:
import time

size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print(f"Time taken using Python lists: {end_time - start_time:.6f} seconds")

array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
result_array = array1 + array2
end_time = time.time()
print(f"Time taken using NumPy arrays: {end_time - start_time:.6f} seconds")


Time taken using Python lists: 0.075876 seconds
Time taken using NumPy arrays: 0.011222 seconds


 Element-wise Multiplication

 • Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000. Measure and Print the time taken for this operation.

 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation

In [61]:
size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print(f"Time taken using Python lists: {end_time - start_time:.6f} seconds")

array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
result_array = array1 * array2
end_time = time.time()
print(f"Time taken using NumPy arrays: {end_time - start_time:.6f} seconds")


Time taken using Python lists: 0.122034 seconds
Time taken using NumPy arrays: 0.006699 seconds


 Dot Product

 • Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and Print the time taken for this operation.

 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [62]:
size = 1000000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

start_time = time.time()
dot_product_list = sum([list1[i] * list2[i] for i in range(size)])
end_time = time.time()
time_list = end_time - start_time

np_array1 = np.array(list1)
np_array2 = np.array(list2)

start_time = time.time()
dot_product_np = np.dot(np_array1, np_array2)
end_time = time.time()
time_np = end_time - start_time

# Output results
print(f"Time taken with Python Lists: {time_list} seconds")
print(f"Time taken with NumPy Arrays: {time_np} seconds")
print(f"Dot product result with Python Lists: {dot_product_list}")
print(f"Dot product result with NumPy Arrays: {dot_product_np}")


Time taken with Python Lists: 0.12789416313171387 seconds
Time taken with NumPy Arrays: 0.0018072128295898438 seconds
Dot product result with Python Lists: 333332833333500000
Dot product result with NumPy Arrays: 333332833333500000


 4. Matrix Multiplication

 • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

 • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.Measure and print the time taken for this operation.

In [65]:
size = 1000
matrix1 = [[i + j for j in range(size)] for i in range(size)]
matrix2 = [[i - j for j in range(size)] for i in range(size)]

start_time = time.time()
result_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
end_time = time.time()
time_list = end_time - start_time

np_matrix1 = np.random.rand(size, size)
np_matrix2 = np.random.rand(size, size)

start_time = time.time()
result_np = np.dot(np_matrix1, np_matrix2)
end_time = time.time()
time_np = end_time - start_time

print(f"Time taken for matrix multiplication using Python lists: {time_list} seconds")
print(f"Time taken for matrix multiplication using NumPy arrays: {time_np} seconds")


Time taken for matrix multiplication using Python lists: 173.02091312408447 seconds
Time taken for matrix multiplication using NumPy arrays: 0.0663137435913086 seconds
